@startuml

abstract class AbstractRateRaram

StepRate <|-- AbstractRateRaram
TOURate <|-- AbstractRateRaram

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml